kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-full-access
  namespace: api
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-read-access
  namespace: api
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs:
    - get
    - list
    - watch
