apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: kv1-dw-hack
  namespace: api
spec:
  provider: azure
  secretObjects:
  - secretName: sqlusername
    data:
    - key: key
      objectName: sqlusername
    type: Opaque
  - secretName: sqlpassword
    data:
    - key: key
      objectName: sqlpassword
    type: Opaque
  parameters:
    keyvaultName: "kv1-dw-hack"       # The name of the Azure Key Vault
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "c24d9ba2-d540-44f7-be09-91af13184fb1" 
    objects:  |
      array:
        - |
          objectName: sqlusername 
          objectType: secret  
        - |
          objectName: sqlpassword 
          objectType: secret                   
    tenantId: "94c83dc3-c5b2-4e3f-a48a-ee9ddbd34865"               # the tenant ID containing the Azure Key Vault instance